_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("polysecure_dataset_train",)
  TEST: ("polysecure_dataset_train",)
  #SOLVER:
  #  STEPS: (210000, 250000)
  #  MAX_ITER: 270000
OUTPUT_DIR: "outputDir"
